name: Weekly Strava report (sync + render + email)

on:
  schedule:
    # Mondays 06:00 UTC (≈ 07:00 Berlin in winter, 08:00 in summer)
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  build-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Sync Strava activities
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          python scripts/strava_sync.py

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore renv
        run: |
          Rscript -e 'install.packages("renv", repos="https://cloud.r-project.org")'
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Render Quarto report
        run: |
          quarto render reports/quarto_template.qmd

      - name: Email report + assets
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Strava weekly report"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          body: "Automated Strava sync completed. Quarto HTML report attached."
          attachments: |
            reports/quarto_template.html
            reports/quarto_template_files/**